# NumPy

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])

In [4]:
arr_1d

array([1, 2, 3, 4, 5])

In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr_float = np.array([1, 2, 3], dtype=np.float64)

In [8]:
arr_float

array([1., 2., 3.])

In [9]:
zeros_arr = np.zeros((5, 4)) 

In [10]:
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
ones_arr = np.ones((3, 3), dtype=int) 

In [12]:
ones_arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
empty_arr = np.empty((4, 4)) 

In [14]:
empty_arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])

In [15]:
identity = np.eye(3) 

In [16]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
range_arr = np.arange(0, 10, 2) 

In [18]:
range_arr

array([0, 2, 4, 6, 8])

In [19]:
linspace_arr = np.linspace(0, 1, 10) 

In [20]:
linspace_arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
random_int = np.random.randint(5, 10, size=(5, 5))

In [22]:
random_int

array([[5, 9, 5, 7, 8],
       [5, 9, 5, 6, 9],
       [9, 7, 6, 6, 8],
       [5, 5, 9, 5, 5],
       [6, 8, 5, 7, 6]])

In [23]:
random_float = np.random.random((3, 4))

In [24]:
random_float

array([[0.21863726, 0.83902398, 0.46084131, 0.096836  ],
       [0.53644517, 0.40933263, 0.92986316, 0.9419283 ],
       [0.42788468, 0.98371451, 0.39722312, 0.82276098]])

In [25]:
normal_dist = np.random.normal(0, 1, (3, 3)) 

In [26]:
normal_dist

array([[-1.4462874 , -1.30233093, -0.23171921],
       [-1.00796085,  0.28133968,  0.61516158],
       [ 1.07342557,  1.22933142, -0.99715015]])

In [27]:
np.random.seed(42)
np.random.randint(1, 5, size=(3, 3))

array([[3, 4, 1],
       [3, 3, 4],
       [1, 1, 3]])

In [28]:
sample_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [29]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
sample_array.shape

(3, 4)

In [31]:
sample_array.size

12

In [32]:
sample_array.max()

12

In [33]:
sample_array.mean()

6.5

In [35]:
sample_array.std()

3.452052529534663

In [36]:
sample_array.var()

11.916666666666666

In [37]:
sample_array.dtype

dtype('int32')

In [38]:
sample_array.ndim

2

In [39]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
sample_array[2]

array([ 9, 10, 11, 12])

In [41]:
sample_array[0]

array([1, 2, 3, 4])

In [42]:
sample_array[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
sample_array[0:2, 1:2]

array([[2],
       [6]])

In [44]:
sample_array[1:2, 0:1]

array([[5]])

In [45]:
sample_array[2:3, 1:3]

array([[10, 11]])

In [46]:
sample_array[0:3, 3:4]

array([[ 4],
       [ 8],
       [12]])

In [47]:
original = np.arange(12) 

In [48]:
original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
original.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
sample_array.reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [52]:
sample_array.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [53]:
sample_array.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [54]:
sample_array.ndim

2

In [55]:
sample_array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
sample_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [57]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [58]:
a

array([1, 2, 3, 4])

In [59]:
b

array([5, 6, 7, 8])

In [60]:
a+b

array([ 6,  8, 10, 12])

In [61]:
a-b

array([-4, -4, -4, -4])

In [62]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [63]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [64]:
a

array([1, 2, 3, 4])

In [65]:
data = np.random.normal(50, 15, 1000)

In [66]:
data

array([36.24759734, 48.1377923 , 19.83555665, 42.60794863, 55.88869626,
       36.06223   , 51.19747718, 47.60725248, 50.3333274 , 43.5831063 ,
       42.02273885, 48.23786747, 53.33118352, 38.48035247, 52.13696904,
       49.48021724, 67.01508898, 48.42881678, 42.12315723, 78.69156907,
       19.59920576, 66.79135417, 61.68788952, 33.48353365, 66.95342291,
       55.59678372, 44.20290574, 32.61844637, 58.4916924 , 39.43319824,
       29.33091044, 44.70325022, 43.07801423, 50.99985918, 47.35571507,
       68.01339158, 60.47598412, 47.42556747, 36.3922013 , 67.8293859 ,
       61.78298187, 89.84015137, 53.9522906 , 74.62656674, 56.9122445 ,
       51.28885207, 27.35064077, 60.82253694, 37.34870115, 42.30011892,
       49.34694796, 45.87048635, 26.55399808, 38.06553512, 63.95876601,
       60.16651115, 60.47660389, 52.60403095, 59.9342677 , 53.61683244,
       47.47692368, 67.47152968, 46.31378469, 38.4549834 , 68.18258513,
       68.50245207, 26.3876707 , 59.56929415, 19.33365467, 66.04

In [67]:
data.mean()

50.48379367763696

In [68]:
data.std()

15.741020138158571

In [69]:
data.shape

(1000,)

In [70]:
data.max()

97.80550007109454

In [71]:
data.min()

-0.4614328969496668

In [72]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

In [73]:
arr1

array([[1, 2],
       [3, 4]])

In [74]:
arr2

array([[5, 6],
       [7, 8]])

In [75]:
arr3

array([[ 9, 10],
       [11, 12]])

In [76]:
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [77]:
np.hstack((arr1, arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#cython
#jython

In [78]:
np.nan

nan